services:
  cody:
    container_name: cody
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/.cody:/home/cody/.cody
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
